name: Deploy kernel to GitHub Pages

on:
  pull_request:
    branches: ["the-wired"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            make \
            grub-common \
            grub-pc-bin \
            xorriso \
            mtools  \
            unzip

      - name: Install cross-compilers
        run: |
          mkdir -p $HOME/i686-elf-tools
          curl -L -o tools.tar.gz https://github.com/lordmilko/i686-elf-tools/releases/latest/download/i686-elf-tools-linux.zip
          unzip tools.zip -d $HOME/i686-elf-tools
          echo "$HOME/i686-elf-tools/bin" >> $GITHUB_PATH

      - name: Verify cross-compilers
        run: |
          i686-elf-gcc --version
          i686-elf-as --version
          i686-elf-ld --version

      - name: Build project
        run: |
          cd src
          make webkernel

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
